### PR TITLE
Update

### PR DESCRIPTION
**Pull request by regeciovad**
Some GUI changes, adding Install button, dnf instead of yum and others.

### CODE REVIEW

**Comment by blaskovic** [comment]
I am not able to get list of my packages with this update.

It gets stuck on around 6% of progress with lot of these tracebacks:

    Traceback (most recent call last):
      File "/home/bblaskov/Repo/dominika-fedora-gooey-karma/src/bodhiworker.py", line 64, in run
        bodhi_update['relevant_packages'] = self.__get_relevant_packages(package.name)
      File "/home/bblaskov/Repo/dominika-fedora-gooey-karma/src/bodhiworker.py", line 129, in __get_relevant_packages
        desktop_pkg = [filename for filename in itertools.chain.from_iterable(installed_pkg)
    TypeError: 'Package' object is not iterable

I have Fedora 21, with dnf-0.6.3-2.fc21.noarch.

**Comment by regeciovad** [comment]
Sorry, it should be working now. Testing on Fedora 20, Fedora 21 (gnome) and Fedora 21 (xfce )

**Comment by blaskovic** [comment]
What should "Remove" button do? I have clicked on it but nothing changed.

Also, there are imported libraries, which are not used.

    import platform
    import getpass
    import koji
    import qrc_resources

Can you please double check it if they are really needed?

**Comment by regeciovad** [comment]
Remove button is fixed and these libraries are not really needed.

**Pull request merged**
